
    
     (Line 0)
     (Line 9)
    "Ontology" ...
    "\n" ...
    <EOF> 
--------------------------------------------------------------------------------
1) RDFXMLParser
2) OWLXMLParser
3) OWLFunctionalSyntaxOWLParser
4) TurtleOntologyParser
5) OWLOBOParser
6) KRSS2OWLParser
7) ManchesterOWLSyntaxOntologyParser
Attribute not found: IRI (Line 26)
Could not parse ontology.  Either a suitable parser could not be found, or parsing failed.  See parser logs below for explanation.
Detailed logs:
Encountered " <ERROR> "< "" at line 1, column 1.
Encountered '<?xml version="1.0" encoding="utf-8"?><rdf:RDF xml:base="http://dbpedia.org/ontology/" xmlns:foaf="http://xmlns.com/foaf/0.1/" xmlns:cc="http://creativecommons.org/ns#" xmlns:vann="http://purl.org/vocab/vann/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:wgs84pos="http://www.w3.org/2003/01/geo/wgs84_pos#" xmlns:cidoccrm="http://purl.org/NET/cidoc-crm/core#" xmlns:wikidata="http://www.wikidata.org/entity/" xmlns:dul="http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#" xmlns:d0="http://www.ontologydesignpatterns.org/ont/d0.owl#" xmlns:owl="http://www.w3.org/2002/07/owl#" xmlns:xsd="http://www.w3.org/2001/XMLSchema#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#" xmlns:prov="http://www.w3.org/ns/prov#" xmlns="http://dbpedia.org/ontology/">' at line 1 column 1.  Expected either 'Ontology:' or 'Prefix:' (Line 1)
Parser: KRSS2OWLParser
Parser: ManchesterOWLSyntaxOntologyParser
Parser: OWLFunctionalSyntaxOWLParser
Parser: OWLOBOParser
Parser: OWLXMLParser
Parser: RDFXMLParser
Parser: TurtleOntologyParser
The following parsers were tried:
Was expecting one of:
Was expecting:
de.uulm.ecs.ai.owlapi.krssparser.ParseException: Encountered "<?xml version=\"1.0\" encoding=\"utf-8\"?>" at line 1, column 1.
org.coode.owlapi.obo.parser.ParseException: Encountered "            </dcterms" at line 10, column 1.
org.semanticweb.owlapi.io.UnparsableOntologyException: Problem parsing file:/home/runner/work/ontology-tracker/ontology-tracker/databus/dbpedia/ontology/data/ontology/dbo-snapshots/2025.04.27-172755/dbo-snapshots.owl
org.xml.sax.SAXParseException; systemId: file:/home/runner/work/ontology-tracker/ontology-tracker/databus/dbpedia/ontology/data/ontology/dbo-snapshots/2025.04.27-172755/dbo-snapshots.owl; lineNumber: 266; columnNumber: 35; XML document structures must start and end within the same entity.
uk.ac.manchester.cs.owl.owlapi.turtle.parser.ParseException: Encountered "" at line 1, column 1.
